language: node_js
node_js:
    - "16"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - yarn
script:
    - yarn run docs:build
cache:
    yarn: true
    directories:
        - "node_modules"
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local-dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: hyuwah/v2
    keep-history: true
    target-branch: master
    on:
        branch: master